language: ruby

sudo: required
dist: trusty
addons:
    postgresql: "9.6"

services:
    - postgresql
    - redis-server

rvm:
  - 2.5.0

env:
  - DB=postgres
  - DISPLAY=:99.0

before_script:
  - psql -c 'create database crowdai_test;' -U postgres

before_install:
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - bundle exec rake parallel:setup
  - bundle exec rake parallel:spec
