default: &default
  host: postgres
  username: postgres
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: crowdai_development

test:
  <<: *default
  database: crowdai_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  database: crowdai_production
  name: crowdai
  password: <%= ENV['CROWDAI_DATABASE_PASSWORD'] %>
